client_config_backend: file
client_config_file: client_secrets.json  # Файл из Google Cloud Console

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json  # Сюда сохранится токен